### ISSUE TITLE
Tech Meetup & Chapter Chengdu Kickoff

### ISSUE THREAD

**Issue by taoshengshi** [ProtoSchool/chengdu#6]
Chengdu is the biggest economy and technical center in south-west China, it is time to setup community to learn, to promote, to research, to develop, and to share ideas of the amazing IPFS technology together! 

I'd like to organize an offline meetup in this month somewhere in Chengdu.Anyone with some good ideas for venues, please post them here :)

Join us in our kickoff meetup, let us start off our adventures together !!! 🚀 🌔😀

**Comment by Z-figaro** [comment]
Can i join the meetup？I have a bunch of question about ipfs

**Comment by taoshengshi** [comment]
> Can i join the meetup？I have a bunch of question about ipfs

Sure, welcome!  please stay turned for the coming news.

**Comment by dongjk** [comment]
Awesome !

**Comment by taoshengshi** [comment]
@Z-figaro @dongjk Please find the events link here: 
http://www.huodongxing.com/event/9499788628100

**Comment by taoshengshi** [comment]
![Presentation1](https://user-images.githubusercontent.com/33315004/60891285-99733c80-a28f-11e9-93a4-d82289ce152e.jpg)

**Comment by dayu26** [comment]
Great! I cannt waiting for launch!

**Comment by taoshengshi** [comment]
recall the meeting (in Chinese Language) :
https://github.com/ProtoSchool/chengdu/blob/master/meetup/07212019/%E6%B4%BB%E5%8A%A8%E5%9B%9E%E9%A1%BE--%E3%80%8E%E5%8D%8F%E8%AE%AE%E5%AD%A6%E9%99%A2%20%C2%B7%20%E6%88%90%E9%83%BD%E5%88%86%E9%99%A2%20%C2%B7%20%E5%BC%80%E9%99%A2%E5%85%B8%E7%A4%BC%E3%80%8F.md
